name: luna_backend

dependencies:
  - python
  - psycopg2
  - pip
  - pip:
    - Django
    - flake8
    - djangorestframework
    - django-filter
    - djangorestframework_simplejwt
    - coreapi
    - gunicorn
    - Pillow
    - django-cors-headers
    - django-countries
    - drf-yasg